## Write a Numpy program to compute the multiplication of two given matrixes

In [5]:
def mat_mul(a,b , cross = False):
    import numpy as np
    if cross:
        return np.cross(a,b)
    return np.dot(a,b)


In [7]:
import numpy as np
a = np.random.rand(3,3)
b = np.random.rand(3,3)
mat_mul(a,b,True)

array([[ 0.06221922,  0.54159608, -0.65068207],
       [-0.0999889 ,  0.55796034, -0.36064767],
       [-0.74870748,  0.23205643,  0.2102005 ]])

## Write a NumPy program to compute the determinant of a given square array

In [9]:
def determinant(arr):
    import numpy as np
    return np.linalg.det(arr)

In [11]:
determinant(a)

-0.08024583581276801

## Write a NumPy program to compute the cross product of two given vectors

In [13]:
mat_mul ([1,2,3],[4,5,6] , True)

array([-3,  6, -3])

## Write a NumPy program to compute the condition number of a given matrix

In [20]:
def condition_number(mat ,p = None):
    import numpy as np
    return np.linalg.cond(mat,p)

In [16]:
condition_number(a)

18.80864154011822

## Write a NumPy program to compute the inverse of a given matrix

In [17]:
np.linalg.inv(a)

array([[ 2.15708711,  0.51012726, -2.35431207],
       [ 2.39890421, -4.59149265,  2.58929047],
       [-3.70596589,  4.33768968, -0.09869587]])